apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: mailer
  POSTGRES_USER: mailer
  POSTGRES_PASSWORD: mailer
  POSTGRES_HOST: postgres
  PGADMIN_DEFAULT_EMAIL: kadabo@gmail.com
  PGADMIN_DEFAULT_PASSWORD: kadabo